config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  post '/sessions' => 'sessions#create', as: 'sessions'
  delete '/logout' => 'sessions#destroy', as: 'logout'

  post '/users' => 'users#create', as: 'users'
  get '/profile' => 'users#profile', as: 'profile'

  get '/trails' => 'trails#index'
  post '/trails' => 'trails#create'
  post '/trails/favorite' => 'trails#favorite'

  get '/notes' => 'notes#index'
  post '/notes' => 'notes#create'


end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :trail
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :trail
  belongs_to :user
end

app/models/trail.rb
class Trail < ActiveRecord::Base
  has_many :notes
  has_many :favorites
  belongs_to :user
  validates_presence_of :coords, :on => :create
  validates_presence_of :description, :on => :create
  validates_presence_of :title, :on => :create
  validates_presence_of :state, :on => :create
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :trails
  has_many :favorites
  authenticates_with_sorcery!
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, email: true
  validates :password, presence: true, length: {minimum: 5, maximum: 10}
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_authenticated
    redirect_to login_path
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.where("trail_id=" + params[:trailId].to_s)
    render :json => @notes.to_json
  end

  def create
    note = Note.new(notes_params)
    current_user.notes << note
    note.save
    render :json => note.to_json
  end

  private

  def notes_params
    params.require(:note).permit(:message, :trail_id, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = login(params[:username], params[:password])
    if user
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

  def index
    @trails = Trail.all
    render :json => @trails.to_json(include: :favorites)
    # render :json => @trails.to_json
  end

  def create
    trail = Trail.create(trail_params)
    ### trail does not have a user id before being created... this gives it one.
    current_user.trails << trail
    render :json => trail.to_json
  end

  def favorite
    favorite = Favorite.new
    current_user.favorites << favorite
    Trail.find(params[:id]).favorites << favorite
    favorite.save
    render :json => favorite.to_json
  end

  private

  def trail_params
    attributes = params.require(:trail).permit(:title, :description, :state)
    coordinates = {coords: arrayify(params.require(:trail).require(:coords))}
    attributes.merge(coordinates)
  end

  def arrayify(hash)
    array = []
    hash.each {|index, coordinates| array[index.to_i] = coordinates}
    array
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:profile]

  def create
    @user = User.new(user_params)
    if @user.save
       render :json => @user.to_json
    else
      @user = @user.errors.full_messages
      render :json => @user.to_json
    end
  end

  def profile
    @trails = current_user.trails
    @favorites = current_user.favorites
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = User.new
    trails = Trail.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrailMap</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,400italic|Josefin+Slab:600,700,600italic' rel='stylesheet' type='text/css'>


</head>
<body>
 <%= render '/shared/nav'%>

<%= yield %>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield :custom_javascript %>

</body>
</html>

app/views/shared/_login.html.erb
<%= form_tag sessions_path do %>
 <%= text_field_tag :username, nil, placeholder: 'Email' %>
 <%= password_field_tag :password, nil, placeholder: 'Password' %>
 <%= submit_tag "Submit", class: 'submitButton'%>
<% end %>

app/views/shared/_nav.html.erb
<nav>
  <h1 class="title"><a href="/">TrailMap</a></h1>
  <% if current_user %>
  <div class="logged_in">
    <div class="logout">
      <h3><a data-method="delete" href="/logout" rel="nofollow">Log Out</a></h3>
    </div>
    <div class="logged_in_as">
      <h3><a href="/profile">Profile</a></h3>
    </div>

  </div>

  <% else %>
  <div class="not_logged_in">
    <div class="signup">
             <h3 class="signup-button">Sign Up</h3>
    </div>
    <div class="login">
      <div class="loginform"><%= render '/shared/login' %></div>
    </div>
    <div class="login">
      <h3 class="login-button">Login</h3>
    </div>

  </div>
  <% end %>


</nav>
  <% if !current_user %>
    <div class="background">
          </div>
      <div class="signup-container">
        <div class="close-signup">X</div>



        <div class="signup">
          <h1>Sign Up</h1>
          <div class="signupform">
            <%= render '/users/form' %>
          </div>
          <div class="errors"></div>
        </div>

      </div>

  <% end %>

app/views/trails/new.html.erb
<h1>Create your trail</h1>

<div id="map-trail">
</div>

<form action="/trails" method="post" id="create-trail-form">
  <%= token_tag %>
  <input class='create-trail-title' type="text" name="trail[title]" placeholder="Title">
  <input class='create-trail-description' type="text" name="trail[description]" placeholder="description">
  <input class='create-trail-state' type="text" name="trail[state]" placeholder="State">
  <input class="current-user-id" type="hidden" value="<%=current_user.id%>">
  <button class='create-trail-button'>Create Trail</button>

</form>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %> (min. one character)
<p>  <%= f.text_field :username, placeholder: 'Username' %></p>
     <%= f.label :email %>
  <p><%= f.text_field :email, placeholder: 'Email' %></p>
  <%= f.label :password %> (min. five characters, max ten characters)
  <p><%= f.password_field :password, placeholder: 'Password' %></p>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h2>Be A User</h2>
<%= render 'form' %>

app/views/users/profile.html.erb
<div class="profile-container">

  <div class="trails-div">
    <h3>My Trails</h3>

    <ul class='trails-ul'>
    <% @trails.each do |trail| %>
      <li class='trail' data-trail-id='<%=trail.id.to_json %>' data-coords='<%= trail.coords.to_json %>' data-title='<%= trail.title.to_json %>' data-state='<%= trail.state.to_json %>' data-description='<%= trail.description.to_json %>'>
        <%= trail.title %>
      </li>
    <% end %>
    </ul>

    <h3>Saved Trails</h3>

    <ul class="favorites-ul">
    <% @favorites.each do |favorite| %>
      <li id='favorite' class='trail' data-trail-id='<%=favorite.id.to_json %>' data-coords='<%= favorite.trail.coords.to_json %>' data-title='<%= favorite.trail.title.to_json %>' data-state='<%= favorite.trail.state.to_json %>' data-description='<%= favorite.trail.description.to_json %>'>
        <%= favorite.trail.title %>, <%= favorite.user.username %>
      </li>
    <% end %>
    </ul>

  </div>  <!-- .trails-div -->

  <div class="notes-div">

    <h3 class="add-notes-here">Trail Notes</h3>

    <ul class="notes-ul"></ul>

    <form action="/notes" method="post" id="create-note-form" class="add-notes-form">
      <%= token_tag %>
      <textarea class="note-form-input" type="text" placeholder="Enter Note" name="note[message]"></textarea>
      <input class="note-form-hidden" type="hidden" name="note[trail_id]" value=''>
      <button class='create-note-button'>Add Note</button>
    </form>

  </div>  <!-- .notes-div -->

  <div class="map-border-div">
    <div class="profile-page-map">

      <div class="trailinfo">
        <h3>Trail info</h3>
        <ul class="trailinfo-ul"></ul>
      </div>

      <button class="create-trail-form-button">New Trail</button>

      <div id="create-trail-form-div">
        <form action="/trails" method="post" id="create-trail-form">
          <%= token_tag %>
          <input class='create-trail-title' type="text" name="trail[title]" placeholder="Title">
          <input class='create-trail-state' type="text" name="trail[state]" placeholder="State">
          <textarea class='create-trail-description' type="text" name="trail[description]" placeholder="description"></textarea>
          <input class="current-user-id" type="hidden" value="<%=current_user.id%>">
          <button class='create-trail-button'>Create Trail</button>
        </form>
          <button class="clear-fields-button">Clear Fields</button>
      </div>

      <div id="map-trail"></div>

    </div>  <!-- .profile-page-map -->
  </div>

</div>  <!-- .profile-container -->

<% content_for :custom_javascript do %>
  <%= javascript_include_tag 'mapCreator'%>
<% end %>

app/views/welcome/index.html.erb
<main>
  <div class="wrap">
    <h1>
      Welcome to Trailmap
    </h1>

   <!--  <p class="signed-in-as">
      You are signed in as  <%= current_user ? current_user.username : '!' %>.
    </p> -->

    <div id="main-map"></div>

    <% content_for :custom_javascript do %>
      <%= javascript_include_tag 'trailsViewer'%>
    <% end %>
  </div>

<!--   <footer></footer>
 -->
</main>